# Generated by Django 3.2.4 on 2021-08-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
