# Generated by Django 3.2.4 on 2021-09-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eduction',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_info',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
