# Generated by Django 3.2.4 on 2021-09-02 07:42

from django.db import migrations, models
import rideshareapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0002_auto_20210901_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='filefield',
            field=models.FileField(default=None, upload_to=rideshareapp.models.nameFile, verbose_name='file_uploaded'),
        ),
    ]
