# Generated by Django 3.2.4 on 2021-08-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0002_auto_20210827_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
