# Generated by Django 3.2.4 on 2021-09-02 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0003_alter_fileupload_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conveyance', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('seats', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='FCMToken',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='carpics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=256, null=True)),
                ('pictures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='rideshareapp.car')),
            ],
        ),
    ]
