# Generated by Django 3.2.4 on 2021-09-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0005_car_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=None)),
                ('pickup', models.CharField(max_length=256)),
                ('dropup', models.CharField(max_length=256)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField()),
                ('is_deleted', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
