# Generated by Django 3.2.4 on 2021-09-03 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0006_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.AddField(
            model_name='trip',
            name='created_on',
            field=models.TimeField(blank=True, default=datetime.time(9, 43, 25, 559090), null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
