# Generated by Django 3.2.4 on 2021-09-03 15:31

from django.db import migrations, models
import rideshareapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0011_alter_trip_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_on',
            field=models.TimeField(blank=True, default=rideshareapp.models.currenttime, null=True),
        ),
    ]
