# Generated by Django 3.2.4 on 2021-09-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0012_alter_trip_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=None)),
                ('message', models.CharField(max_length=256)),
                ('stars', models.IntegerField(blank=True, default=None)),
            ],
        ),
    ]
