# Generated by Django 3.2.4 on 2021-09-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0013_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
