# Generated by Django 3.2.4 on 2021-09-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0014_user_fcm'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('message', models.CharField(max_length=256)),
                ('senderid', models.CharField(max_length=256)),
                ('receiverid', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='user_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='stars',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user_id',
            field=models.CharField(max_length=256),
        ),
    ]
