# Generated by Django 3.2.4 on 2021-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0015_auto_20210907_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(help_text='type of text', max_length=256),
        ),
    ]
