# Generated by Django 3.2.4 on 2021-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0016_alter_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(max_length=256),
        ),
    ]
