# Generated by Django 3.2.4 on 2021-09-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0017_alter_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='FCMToken',
        ),
    ]
